import Head from 'next/head'
import { Hero, NavBar, EntryPreview } from '../components'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
        <Hero />
      <div className="px-5">
      <div>
        Últimos Episodios
      </div>
        <ul>
          <EntryPreview />
        </ul>
      </div>

    </div>
  )
}
