import Head from "next/head";
import { db } from "../utils/firebase";
import { collection, getDocs, query, orderBy } from "firebase/firestore";
import { Hero, NavBar, EntryPreview } from "../components";
import { useEffect, useState } from "react";

import { getPosts } from "../api/posts";

export const getAllPosts = async () => {
  const postsList = [];
  const q = query(collection(db, "posts"), orderBy("date_creation", "desc"));
  const querySnapshot = await getDocs(q);
  querySnapshot.forEach(doc => {
    postsList.push({ ...doc.data(), id: doc.id });
  });
  return postsList;
};

export default function Home() {
  const [posts, setPosts] = useState([]);

  const fetchPosts = async () => {
    const posts = await getAllPosts();
    setPosts(posts);
  }

  useEffect(() => {
    getPosts()
    fetchPosts()
  }, []);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar />
      <Hero />
      <div className="px-5">
        <div>Últimos Episodios</div>
        <ul>
          <EntryPreview />
        </ul>
      </div>
    </div>
  );
}
